### ISSUE TITLE
Bug in model.py?

### ISSUE THREAD

**Issue by wddabc** [glample/tagger#18]
Hi, great work to begin with!

I'm wondering there might a bug in your https://github.com/glample/tagger/blob/master/model.py#L244, where it will break when I turn off the char_lstm (setting char_dim=0 I think?). The reason is the input now has only one element and pass the check in L244 as a list and cause error in L252. I think the right way is either removing the check or replacing with:
`inputs = T.concatenate(inputs, axis=1) if len(inputs)!=1 else inputs[0]
`

**Comment by arpit1997** [comment]
>I'm wondering there might a bug in your https://github.com/glample/tagger/blob/master/model.py#L244, where it will break when I turn off the char_lstm (setting char_dim=0 I think?). The reason is the input now has only one element and pass the check in L244 as a list and cause error in L252. I think the right way is either removing the check or replacing with:
inputs = T.concatenate(inputs, axis=1) if len(inputs)!=1 else inputs[0]
No it won't break the code

**Comment by glample** [comment]
Sorry for the delay.. There was a small bug indeed, thank you for spotting it. Your fix was correct, I pushed it here: https://github.com/glample/tagger/commit/c735605fc2218975019aca04bd64796ac4f363bd
