### ISSUE TITLE
Can you also provide your train.txt, dev.txt, test.txt file as well?

### ISSUE THREAD

**Issue by leefionglee** [glample/tagger#2]
Hi,

Good work!!  Can you also provide these train.txt, dev.txt and test.txt for training your model used in your paper?   Thanks a lot!!

**Comment by zero76114** [comment]
@glample : Can you help us?
Your work is completely new and interesting. I am really new with Python and Theano, so I don't know how I can rerun your work. Please help me more detail.
Thanks

**Comment by a455bcd9** [comment]
@leefionglee I think it's this data set: http://www.cnts.ua.ac.be/conll2003/ner/

>  The English data is a collection of news wire articles from the Reuters Corpus. The annotation has been done by people of the University of Antwerp. Because of copyright reasons we only make available the annotations. In order to build the complete data sets you will need access to the Reuters Corpus. It can be obtained for research purposes without any charge from NIST.

**Comment by zero76114** [comment]
@a455bcd9 Thank you. I try to download and preprocessing data Conll2003 and after I get 3 file for English Reuter: eng.train, eng.testa and eng.testb.
@glample can you show me how i can change train.txt , dev.test and test.txt;

**Comment by prashant-puri** [comment]
@glample Hey can you help me with creation of train.txt , dev.test and test.txt.
@zero76114 Hey can you help me with creation of train.txt , dev.test and test.txt.

**Comment by Zhangzirui** [comment]
@zero76114  Hi, can you help me with creation of train.txt , dev.test and test.txt.
@prashant-puri  Hi, can you help me with creation of train.txt , dev.test and test.txt.

**Comment by glample** [comment]
The dataset is now available on the repo.

**Comment by kewlcoder** [comment]
@**glample** - Sir, if I am not wrong, the dataset you provided,namely, **eng.train, eng.testa **and** eng.testb** is free but copywrited by [Reuters](http://trec.nist.gov/data/reuters/reuters.html).
I would like to suggest you to add this warning to that particular commit so that people take proper precautions before using it.
