### ISSUE TITLE
Format of input file for tagger.py

### ISSUE THREAD

**Issue by Justin1904** [glample/tagger#20]
Just want to make sure: in the README it says input file for tagger.py should contain 1 sentence each line and sentences have to be tokenized. So, I wonder if 'tokenized' here means the sentences are split into tokens and tokens are separated by space?

**Comment by glample** [comment]
Yes, this is exactly what it means. The input for the training and tagger scripts are not the same. For the training it's one word by line (followed by its tags), and for tagger.py this is what you described.

**Comment by xukai504087493** [comment]
"sentences have to be tokenized"
I still don't understand what dose this means.
could you please show me an example of the input.txt sentence format.
here is my example: 
input: Wonderful day ! isn't it?
output: Wonderful__O day__O !__O isn't__O it?__O

**Comment by xukai504087493** [comment]
seems all output are " _O"
