### ISSUE TITLE
would you like provide some demo dataset like train.txt, dev.txt, text.txt, input.txt?

### ISSUE THREAD

**Issue by SeekPoint** [glample/tagger#21]
or the URL of those resource

**Comment by guotong1988** [comment]
same question, thanks

**Comment by guotong1988** [comment]
https://github.com/glample/tagger/issues/2

**Comment by glample** [comment]
Fixed in 3b2fc49fcc510d7a86a7848cd01fe11c2ee5b75b

**Comment by SeekPoint** [comment]
@glample 

is this reasonable like 
python train.py --train dataset/eng.train --dev dataset/eng.testb --test dataset/eng.testa
?

**Comment by glample** [comment]
eng.testa is the dev
eng.testb is the test

**Comment by Rabia-Noureen** [comment]
Hi @glample @loveJasmine   i am trying to train the model using
python train.py --train dataset/eng.train --dev dataset/eng.testa --test dataset/eng.testb  --lr_method=adam --tag_scheme=iob
but i got the following error. Can you please help me resolve that error?I am stuck...
46533/51362 (90.59811%)
Traceback (most recent call last):
  File "train.py", line 220, in <module>
    dev_data, id_to_tag, dico_tags)
  File "C:\Users\Acer\Anaconda2\tagger\utils.py", line 282, in evaluate
    return float(eval_lines[1].strip().split()[-1])
IndexError: list index out of range
