### ISSUE TITLE
CRF likelihood

### ISSUE THREAD

**Issue by xuewei4d** [glample/tagger#22]
It seems there is a little difference in CRF [likelihood](https://github.com/glample/tagger/blob/master/nn.py#L258) loss from in [TensorFlow](https://github.com/tensorflow/tensorflow/blob/6b1d4fd8090d44d20fdadabf06f1a9b178c3d80c/tensorflow/contrib/crf/python/ops/crf.py#L272) . The unary potentials are in log_sum_exp, while in TF, it is outside.

**Comment by glample** [comment]
Thank you for spotting this. I think this should not make a big difference though.
