### ISSUE TITLE
How to train LSTM CRF using my own pre-trained Word2Vec vectors 

### ISSUE THREAD

**Issue by kewlcoder** [glample/tagger#23]
Hi,
  LSTM-CRF internally uses the vector representations created using the Word2Vec algorithm. Right?

How to feed LSTM-CRF with my home-baked Word2Vec vectors?

Thanks
Kewl

**Comment by glample** [comment]
Hi,

It actually uses wang2vec vectors, not word2vec: https://github.com/wlin12/wang2vec
To use your own set of word embeddings you have to train another model, and use the "--pre_emb" parameter to set the location of the vectors you want to use.

**Comment by kewlcoder** [comment]
Okay, Thanks a ton ! Would give it a try.

**Comment by kewlcoder** [comment]
Hi GLample,
       As suggested above, I am trying to train using my home-baked word2vec vectors using the command -
**./train.py --train dataset/eng.train -d dataset/eng.testa -p /home/admin/aman/models/wiki_20161101/0g_23g/best_results/googleBin --test dataset/eng.testb**

Here, "**googleBin**" is my word2vec vectors file generated using "**gensim**" function **load_word2vec_format()** -
Gensim says, "_The model can be stored/loaded via its save() and load() methods, or stored/loaded in a format compatible with the original word2vec implementation via save_word2vec_format() and **load_word2vec_format()**._"

Question - 
1. is the "--pre_emb" option compatible with the google original word2vec implementation format? If yes, do we need to specify word_dim explicitly?

2. if not compatible, what is the format of embeddings file that it takes?


FYI, the **error** I am getting is -
_Loading pretrained embeddings from
<full path>....googleBin...
Traceback (most recent call last):
  File "./train.py", line 162, in <module>
    ) if not parameters['all_emb'] else None
  File "...../loader.py", line 169, in augment_with_pretrained
    for line in codecs.open(ext_emb_path, 'r', 'utf-8')
  File "/root/anaconda2/lib/python2.7/codecs.py", line 699, in next
    return self.reader.next()
  File "/root/anaconda2/lib/python2.7/codecs.py", line 630, in next
    line = self.readline()
  File "/root/anaconda2/lib/python2.7/codecs.py", line 545, in readline
    data = self.read(readsize, firstline=True)
  File "/root/anaconda2/lib/python2.7/codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbd in position 0: invalid start byte_

Thanks

**Comment by kewlcoder** [comment]
It finally worked for me when I input a text file having format
<word>  <vector>\n
e.g. - for a 2 dimensional vector

the -0.0236 0.5287
a .09379 -0.3417
.....

NOTE - lines not having "word_dim + 1" words are ignored.
Also, it seems one needs to necessarily specify the word_dim.
The code doing this can be found from the line 164 onwards in [model.py](https://github.com/glample/tagger/blob/master/model.py)

```
 if pre_emb and training:
                new_weights = word_layer.embeddings.get_value() 
```

**Comment by Rabia-Noureen** [comment]
Hi @kewlcoder  I am new to python can you please help me out with training the model using GoogleNews word embeddings? I am trying to train using the script

python train.py --train dataset/eng.train --dev dataset/eng.testa --test dataset/eng.testb --lr_method=adam --tag_scheme=iob --pre_emb=GoogleNews-vectors-negative300.bin --all_emb=300

I am using the dataset that is already provided with the system.
I got the error:
![image](https://user-images.githubusercontent.com/29410483/31252396-83276c7a-aa3a-11e7-83a0-3160065f259c.png)

**When i tried to train the model with out the word embedding i got an other error**
(env_name27) C:\Users\Acer\tagger-master>python train.py --train dataset/eng.train --dev dataset/eng.testa --test dataset/eng.testb
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GT 620M (CNMeM is enabled with initial size: 85.0% of memory, cuDNN not available)
Model location: ./models
Found 23624 unique words (203621 in total)
Found 84 unique characters
Found 17 unique named entity tags
14041 / 3250 / 3453 sentences in train / dev / test.
Saving the mappings to disk...
Compiling...
Starting epoch 0...
50, cost average: 15.406189
100, cost average: 11.704297
150, cost average: 10.767459
200, cost average: 13.812738
250, cost average: 11.460194
300, cost average: 13.207466
350, cost average: 12.146099
400, cost average: 12.428576
450, cost average: 10.977689
500, cost average: 12.830771
550, cost average: 10.062991
600, cost average: 9.834551
650, cost average: 11.481623
700, cost average: 9.460655
750, cost average: 9.907359
800, cost average: 10.251657
850, cost average: 10.405848
900, cost average: 14.113665
950, cost average: 10.436158
'.' is not recognized as an internal or external command,
operable program or batch file.
ID     NE  Total      O  S-LOC  B-PER  E-PER  S-ORG S-MISC  B-ORG  E-ORG  S-PER  I-ORG  B-LOC  E-LOC B-MISC E-MISC I-MISC  I-PER  I-LOC  Percent
 0      O  42759  42759      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0  100.000
 1  S-LOC   1603   1603      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 2  B-PER   1234   1234      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 3  E-PER   1234   1234      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 4  S-ORG    891    891      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 5 S-MISC    665    665      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 6  B-ORG    450    450      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 7  E-ORG    450    450      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 8  S-PER    608    608      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
 9  I-ORG    301    301      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
10  B-LOC    234    234      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
11  E-LOC    234    234      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
12 B-MISC    257    257      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
13 E-MISC    257    257      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
14 I-MISC     89     89      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
15  I-PER     73     73      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
16  I-LOC     23     23      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0    0.000
42759/51362 (83.25026%)
Traceback (most recent call last):
  File "train.py", line 220, in <module>
    dev_data, id_to_tag, dico_tags)
  File "C:\Users\Acer\tagger-master\utils.py", line 282, in evaluate
    return float(eval_lines[1].strip().split()[-1])
IndexError: list index out of range

**I am doing something wrong?I am stuck with this issue for about 2 months and couldn't resolve it. Thanks in advance.**

**Comment by Rabia-Noureen** [comment]
@kewlcoder also please mention that how did you managed to convert your word embedding into a text file?
