### ISSUE TITLE
How to generate files " *.mat "

### ISSUE THREAD

**Issue by SophiaCY** [glample/tagger#24]
Hi.
I'm a novice in NER and I'm trying to use the code to deal with Chinese NER task. However, after running train.py all files I got were just "parameters.pkl" and "mappings.pkl". So when I tried to run tagger.py, it said that it needed "word_layer.mat". 
So how can I generate files " *.mat ".?

Thanks a lot.

**Comment by glample** [comment]
Hi,

You have to wait a little bit that the model completes one epoch. At the end of each epoch the tagger will compute the scores, and save the model if this is the best score on the validation set so far (which is always the case at the end of the first epoch). It will then generate the *.mat files.
