### ISSUE TITLE
Forget gate code commented out in LSTM

### ISSUE THREAD

**Issue by lczarne** [glample/tagger#25]
Why LSTM implementation in nn.py have forget gate code commented out? It seems that even in tagging code there is no forget gate usage. Shouldn't it be used in LSTM?

**Comment by glample** [comment]
Yes, in the original LSTM implementation there is a proper forget gate. Here, we simply define `f_t = 1 - i_t`. We observed that this does not significantly change the results, and makes the model slightly faster.
