### ISSUE TITLE
Comment in train.py misleading

### ISSUE THREAD

**Issue by ronxin** [glample/tagger#27]
[Line 168 of train.py](https://github.com/glample/tagger/blob/master/train.py#L168) reads 

    # Create a dictionary and a mapping for words / POS tags / tags

But in fact, POS tags seem to have been never used.

**Comment by kewlcoder** [comment]
I have a similar doubt.
Does the tagger use PoS tags as an input feature for NER ?

**Comment by glample** [comment]
No they are not used. Sorry for the confusion. We were originally using POS tags, but as it was not really improving results for English (and also to make the model more general), we decided to ignore them. But I didn't remove this part of the code.
