### ISSUE TITLE
Does the tagger use PoS tags as an input feature for NER ?

### ISSUE THREAD

**Issue by kewlcoder** [glample/tagger#29]
Does the tagger use PoS tags available in the Conll dataset as an input feature for NER ?

What are the input features, apart from the word embeddings, used by the tagger?

**Comment by glample** [comment]
It does not use the POS tags, only the words. We tried to use POS tags, it was helpful for Dutch and German, but not so much for English and Spanish.

**Comment by kewlcoder** [comment]
Thanks a lot Sir !
