### ISSUE TITLE
Increasing the number of worker threads/core to be used

### ISSUE THREAD

**Issue by kewlcoder** [glample/tagger#30]
Hi,
   Currently run of Tagger on my 24 core CPU uses 8-12 core instead of the full 24.
gensim gives an option of utilizing the full cores of CPU. 
Is there an option possible for tagger as well? This would really speed it up.

**Comment by glample** [comment]
Hi,
Actually in my experience, using a single thread was always faster than using multi-threading. The reason for this is that the tagger is not batched, I guess.

**Comment by sbmaruf** [comment]
@kewlcoder  : As tensorflow/theano computes everything on the symbolic graph, each time the graph is fed with data, the calculation has been done on gpu/cpu. For smaller batch, transferring time of data to gpu/cpu bus bottleneck the overall computation time. So if you have smaller batch single thread will be best. Even sometimes codes run faster on CPU than a titan X gpu for this reason.

**Comment by glample** [comment]
Yes for me the tagger was faster on CPU than on GPU (I had K40 at the time). The tagger could definitely be batched, but I did not do it as the datasets were small enough and training can already be done in a few hours.
