### ISSUE TITLE
Reproducing the result for the LSTM-CRF model

### ISSUE THREAD

**Issue by ronxin** [glample/tagger#31]
I am trying to reproduce the reported result for the LSTM-CRF model on the English dataset included in the repository, but haven't yet succeeded in getting the reported F1 score (90.94).

I used all the default parameter values, which seem to match what is in the paper, and I used eng.train for training, eng.testa for validation, and eng.testb for testing. After the program stopped (100 epochs on the training set), I got the best dev score to be 89.74, and the corresponding test score is 83.55. Am I missing something?

Also, in `train.py`, why is "**New best score on test**" reported? Shouldn't one only report the test score of the model that does the best on validation?

I will keep checking if I have anything misconfigured, but at the meantime, any help or insight would be appreciated! Thanks again for the awesome paper + code!

**Comment by ronxin** [comment]
I realized that I did not yet use a pre-trained word embedding. I suppose that is part of the reason.

**Comment by Janiknoah** [comment]
Dear @ronxin, did that help? 
I tried to use that model http://devmount.github.io/GermanWordEmbeddings/     (german.model) but that didnt work. I am not even sure what kind of file/ model is needed. Could you give me a hint?

**Comment by Rabia-Noureen** [comment]
Hi @ronxin  @JuliMinou  i want to use Publicly available word vectors trained from Google News as pre-trained word embeddings available at https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing

Its a .gz file, but i dont have any idea how to use those word embeddings in my script.
python train.py --train dataset/eng.train --dev dataset/eng.testa --test dataset/eng.testb --lr_method=adam --tag_scheme=iob

Can you please guide me?I am stuck...

**Comment by glample** [comment]
Hello,

You can find a link to all the embeddings we used in the paper here: https://github.com/glample/tagger/issues/44
