### ISSUE TITLE
Is there any way to make tagging faster?

### ISSUE THREAD

**Issue by lczarne** [glample/tagger#36]
Is there some way to trade prediction quality for tagging speed? Right now it gives very good results but works extremely slow. What could be done to make the architecture more speed-oriented?

**Comment by glample** [comment]
What is the speed you get? It should not be that slow. Training without CRF will make it a bit faster, and will decrease the quality.

Also, the tagger should be run on CPU, it will be faster than on GPU. It's also better to use 1 CPU core only. The fastest if you have N cores is to split the dataset you want to tag in N files, and apply the tagger N times (one for each file, using 1 CPU only).
