### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by Jacksonlark** [glample/tagger#37]
When running train.py using owner dataset, exception happend.

I don't know how to find exception location, please give me some suggest

output look like these:

Model location: ./models/tag_scheme=iob,lower=False,zeros=False,char_dim=25,char_lstm_dim=25,char_bidirect=True,word_dim=100,word_lstm_dim=100,word_bidirect=True,pre_emb=,all_emb=False,cap_dim=0,crf=True,dropout=0.5,lr_method=sgd-lr_.005
Found 107161 unique words (1038059 in total)
Found 5360 unique characters
Found 27 unique named entity tags
348944 / 349324 / 350017 sentences in train / dev / test.
Saving the mappings to disk...
Compiling...
Starting epoch 0...
50, cost average: 9.245738
100, cost average: 9.109227
150, cost average: 8.605217
200, cost average: 7.075110
250, cost average: 7.567110
300, cost average: 6.226210
350, cost average: 6.570437
400, cost average: 6.829048
450, cost average: 6.786608
500, cost average: 6.878631
550, cost average: 6.116019
600, cost average: 5.965092
650, cost average: 6.305119
700, cost average: 6.422719
750, cost average: 5.528729
800, cost average: 5.219546
850, cost average: 6.256534
900, cost average: 5.553740
950, cost average: 6.382971
 Floating point exception (core dumped)

**Comment by a455bcd9** [comment]
Hey, have a look at this, may help you: https://github.com/glample/tagger/issues/10

**Comment by Jacksonlark** [comment]
@a455bcd9 Thank you! It is helpful!
