### ISSUE TITLE
Pre-trained word embedding for German/Spanish/Dutch/French

### ISSUE THREAD

**Issue by dungtn** [glample/tagger#46]
Hi @glample,

Do you use any pre-trained embedding for languages other than English? If so, where I can download these embeddings?

Thanks,
Dung Thai

**Comment by s7kjd3** [comment]
https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md

**Comment by Rabia-Noureen** [comment]
Hi @dungtn @SawyerW  i want to use Publicly available word vectors trained from Google News as pre-trained word embeddings available at https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing 

Its a .gz file, but i dont have any idea how to use those word embeddings in my script. 
python train.py --train dataset/eng.train --dev dataset/eng.testa --test dataset/eng.testb  --lr_method=adam --tag_scheme=iob

Can you please guide me?I am stuck...

**Comment by s7kjd3** [comment]
Since your pre-trained word embedding comes from word2vec, you can use " gensim.models.KeyedVectors.load_word2vec_format" .
You can find what you need from here: https://radimrehurek.com/gensim/models/word2vec.html

**Comment by JohnGiorgi** [comment]
@Rabia-Noureen 

I wrote a (very) simple script a little while ago to achieve exactly what you are looking to do. It it based directly off the documentation @SawyerW links to. 

You can grab the script [here](https://github.com/JohnGiorgi/NER-model-data-preprocessing/blob/master/convert_w2v_bin_to_glove_format.py). Just make sure you haven `genism` installed by running either:

`easy_install -U gensim` or `pip install --upgrade gensim`

And make sure to first unzip the `.gz` file. 

To use, just open the script and set `binary_w2v_file_path` to the location of your unzipped`.bin` file. By default the script will save the converted embeddings in the directory you called the script from (although you can also change this in the script). Then run the script: `python convert_w2v_bin_to_glove_format.py` in the terminal.

(I confirmed the script works with the word vectors you linked to)

**Comment by Rabia-Noureen** [comment]
@JohnGiorgi  @SawyerW  Thanks a lot for your quick response i appreciate your suggestions. I will try the script and will get back to you if i need any further help in this regard.

Thanks again

**Comment by Rabia-Noureen** [comment]
@JohnGiorgi Sorry my file was .tar not .gz and i am using Windows 10 with python 2.7. I tried to update your script according to my file name and path as shown below

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
from gensim.models.keyedvectors import KeyedVectors

############################# INSTRUCTIONS #############################
# 1) Set binary_w2v_file_path, the path to the file in C binary (w2v)
# format to be converted to glove format.
# 2) (OPTIONAL) provide an output directory when calling convert_bin_to_glove()
# to save the converted word vectors. Defaults to whatever directory the
# script was called from.
########################################################################

def convert_bin_to_glove(input_file, output_file_path=os.getcwd()):
	# check that input_file has extension .bin
	assert input_file.endswith('.tar'), "You need to provide a .bin file!"
	# load word vectors provided in C binary format
	word_vectors = KeyedVectors.load_word2vec_format(binary_w2v_file_path, binary=True)
	# load vocab from word vectors
	vocab = word_vectors.vocab
	# write contents of input_file to new file at output_file_path in glove format
	with open(output_file_path + '/converted_word_vectors.txt', 'w+') as f:
		for word in vocab:
			vector = word_vectors[word]
			f.write("%s %s\n" %(word, " ".join(str(v) for v in vector)))

if __name__ == '__main__':
	# path to word vectors in binary c format
	binary_w2v_file_path = "C:/Users/Acer/Anaconda2/tagger/Word/mpqa_2_0_database.tar"
	convert_bin_to_glove(binary_w2v_file_path)

but i got the following error

(env_name27) C:\Users\Acer\Anaconda2\tagger>python convert_w2v_bin_to_glove_format.py
C:\Users\Acer\Anaconda2\envs\env_name27\lib\site-packages\gensim-2.3.0-py2.7-win32.egg\gensim\utils.py:865: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Traceback (most recent call last):
  File "convert_w2v_bin_to_glove_format.py", line 30, in <module>
    convert_bin_to_glove(binary_w2v_file_path)
  File "convert_w2v_bin_to_glove_format.py", line 18, in convert_bin_to_glove
    word_vectors = KeyedVectors.load_word2vec_format(binary_w2v_file_path, binary=True)
  File "C:\Users\Acer\Anaconda2\envs\env_name27\lib\site-packages\gensim-2.3.0-py2.7-win32.egg\gensim\models\keyedvectors.py", line 205, in load_word2vec_format
    with utils.smart_open(fname) as fin:
  File "C:\Users\Acer\Anaconda2\envs\env_name27\lib\site-packages\smart_open-1.5.3-py2.7.egg\smart_open\smart_open_lib.py", line 140, in smart_open
    return file_smart_open(parsed_uri.uri_path, mode)
  File "C:\Users\Acer\Anaconda2\envs\env_name27\lib\site-packages\smart_open-1.5.3-py2.7.egg\smart_open\smart_open_lib.py", line 644, in file_smart_open
    return compression_wrapper(open(fname, mode), fname, mode)
IOError: [Errno 2] No such file or directory: 'C:/Users/Acer/Anaconda2/tagger/Word/mpqa_2_0_database.tar'

I am doing something wrong?

**Comment by Rabia-Noureen** [comment]
Hi @JohnGiorgi  i tried to run the script but i got this error

![image](https://user-images.githubusercontent.com/29410483/30180670-b4544a90-9421-11e7-8a12-4eb7009dbf8f.png)

I tried this for changing the permissions
![image](https://user-images.githubusercontent.com/29410483/30180865-59d2dc3e-9422-11e7-9e7f-c6365523ba3e.png)

but no use..... Can you please suggest some other way regarding the permissions?

**Comment by s7kjd3** [comment]
@Rabia-Noureen , got no idea why you try to convert the word2vec embedding. Why don't you just use the word2vec embedding directly? 

    word2vec_model = gensim.models.KeyedVectors.load_word2vec_format(
        '/path/GoogleNews-vectors-negative300.bin.gz', binary=True)
    word2vec_model.init_sims(replace=True)
then you can find all the embedding with word2vec_model.vocab

**Comment by Rabia-Noureen** [comment]
@SawyerW  actually i have just started with python and i was trying to train the model. I dont have any idea where should i embed the code in NERtagger    

word2vec_model = gensim.models.KeyedVectors.load_word2vec_format(
    '/path/GoogleNews-vectors-negative300.bin.gz', binary=True)
word2vec_model.init_sims(replace=True)

I would highly appreciate if you can guide me....

**Comment by s7kjd3** [comment]
Maybe it is a good idea if you can post your code and show us what you want to do.

**Comment by Rabia-Noureen** [comment]
@SawyerW  I am actually trying to use this project NER tagger as it is, in order to train the model i am using iob tag scheme and adam as learning method

python train.py --train dataset/eng.train --dev dataset/eng.testa --test dataset/eng.testb --lr_method=adam --tag_scheme=iob  

Now i have to use the pre-trained word embedding for training using GoogleNews-vectors-negative300.bin.gz

**Comment by glample** [comment]
You can find all pretrained embeddings used in the paper here: https://github.com/glample/tagger/issues/44
