### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Kidanew** [glample/tagger#47]
Dear Glample,

When I have tried to train the model it renders the following error: FileNotFoundError: [WinError 3] The system cannot find the path specified: './models\tag_scheme=iobes,lower=False,zeros=False,char_dim=25,char_lstm_dim=25,char_bidirect=True,word_dim=100,word_lstm_dim=100,word_bidirect=True,pre_emb=,all_emb=False,cap_dim=0,crf=True,dropout=0.5,lr_method=sgd-lr_.005'

Thus, this is to kindly request you how to fix this error and train the model with custom dataset. Thank you very much for your consideration and support.
 
With Regards,
Kidane W.

**Comment by DivJ** [comment]
Dear Kidanew
To resolve this issue delete following line from model.py
line 40: `model_path = os.path.join(models_path, self.name)`

and instead write
`model_path=models_path`


Hope it helps

**Comment by Kidanew** [comment]
Thanks Glample,
That was the case, thank you very much!!!
