### ISSUE TITLE
Error on Spanish dataset

### ISSUE THREAD

**Issue by afcruzs** [glample/tagger#51]
Hi, 

I was using conll2002 dataset in spanish and when it was computing the F1 score it failed like this:

```
Traceback (most recent call last):
  File "train.py", line 220, in <module>
    dev_data, id_to_tag, dico_tags)
  File "D:\deepner\tagger\utils.py", line 282, in evaluate
    return float(eval_lines[1].strip().split()[-1])
IndexError: list index out of range
```

The dataset is this one: http://www.cnts.ua.ac.be/conll2002/ner/data/
And I run the following command: python train.py --train dataset\esp.train --dev dataset\esp.testa --test dataset\esp.testb

Thank you for sharing this implementation 👍

**Comment by Rabia-Noureen** [comment]
Hi @afcruzs were you able to solve this error?I am getting exactly the same error using the data set provided in this project NER tagger. I am new to python and I am stuck with this error for the past 5 days :(
@glample any suggestions please?
