### ISSUE TITLE
Training new model

### ISSUE THREAD

**Issue by ghost** [glample/tagger#54]
I am trying to train my own model and I am not able to go through this error which is being generated , 
![capture](https://user-images.githubusercontent.com/6318396/27653047-e120899c-5c0b-11e7-9e6d-bd7d882be6c4.PNG)

I am not able to figure it out why i am getting that error.

**Comment by ghost** [comment]
My evaluate function is returning empty eval_lines list.

**Comment by ghost** [comment]
it seems like the below shell command we are trying to run utils.py has some issue
os.system("%s < %s > %s" % (eval_script, output_path, scores_path)).

**Comment by yuchenlin** [comment]
the code is for linux environment

**Comment by ghost** [comment]
thanks yuchenlin, i figured that one out earlier.  But my model is predicting everything O, can you help me on that why thats happening?

**Comment by Rabia-Noureen** [comment]
Hi @sandeeppilania   I am new to python can you please help me out with training the model using GoogleNews  word embeddings? I am trying to train using the script

python train.py --train dataset/eng.train --dev dataset/eng.testa --test dataset/eng.testb --lr_method=adam --tag_scheme=iob --pre_emb=GoogleNews-vectors-negative300.bin --all_emb=300

**I got this error:**
![image](https://user-images.githubusercontent.com/29410483/31172015-59b1d558-a91b-11e7-9ed0-d255f55e06c0.png)

I am stuck with this issue for about 2 months and couldn't resolve it. Thanks in advance.

**Comment by Rabia-Noureen** [comment]
@sandeeppilania i am experiencing the same error can you please guide me how you were able to solve it? I have posted mine on https://github.com/glample/tagger/issues/62.
