### ISSUE TITLE
IOError: [Errno 2] No such file or directory: './evaluation/temp/eval.1733948.scores'

### ISSUE THREAD

**Issue by fresh1993** [glample/tagger#60]
**_When I was training, I encountered the following error._**
Score on dev: 0.00000
Score on test: 0.00000
New best score on dev.
Saving model to disk...
New best score on test.
1000, cost average: 10.348209
1050, cost average: 12.143117
1100, cost average: 8.300045
1150, cost average: 9.993797
1200, cost average: 10.771072
1250, cost average: 9.085944
1300, cost average: 7.899846
1350, cost average: 9.960074
1400, cost average: 10.100777
1450, cost average: 11.571788
1500, cost average: 8.144207
1550, cost average: 10.256949
1600, cost average: 8.761736
1650, cost average: 10.398692
1700, cost average: 8.837197
1750, cost average: 9.407584
1800, cost average: 13.434276
1850, cost average: 8.269768
1900, cost average: 9.626532
1950, cost average: 11.335016
Traceback (most recent call last):
  File "./train.py", line 220, in <module>
    dev_data, id_to_tag, dico_tags)
  File "/home/jq/software/tagger-master/utils.py", line 255, in evaluate
    eval_lines = [l.rstrip() for l in codecs.open(scores_path, 'r', 'utf8')]
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: './evaluation/temp/eval.1733948.scores'

**Comment by PCR11** [comment]
Hi,  i have the same problem with you ,are you solved it?
