### ISSUE TITLE
Pretrained skip-n-gram vector

### ISSUE THREAD

**Issue by sbmaruf** [glample/tagger#63]
Hello @glample,

I got the pre-trained vector from https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md this link.

I was wondering how can I get the pretrained skip-n-gram model vector? I haven't found any suitable resource. The paper(http://arxiv.org/abs/1603.01360) mentioned that they used skip-n-gram model, not the skip-gram model.

**Comment by glample** [comment]
Hi,

You can find the tool we used on this repo: https://github.com/wlin12/wang2vec
Look for structured skipngram (option 3)

Guillaume

**Comment by sbmaruf** [comment]
On which dataset you have used for skipngram?

**Comment by glample** [comment]
We used the last version of the English Gigaword.

**Comment by sbmaruf** [comment]
Thank you glample.

**Comment by perceptronnn** [comment]
Do you have any idea about where can I get pre-trained skip-n-gram vectors?

**Comment by sbmaruf** [comment]
@anurag25  Please take a look in this issue,

https://github.com/glample/tagger/issues/44
