### ISSUE TITLE
How to train large quantities of data

### ISSUE THREAD

**Issue by qiansi** [glample/tagger#66]
hi，I would like to train more named entities, via more data, about 10 types of entities, 50M of data, but will crash whether through GPU or CPU memory. Is there any solution?

**Comment by glample** [comment]
Hi,

50M of data is small, this should not crash. What is the problem you get?

**Comment by qiansi** [comment]
@glample Thank you for your reply. You are right. I was having a problem with the sentence. I treated all the input as an entire sentence. Now that I have solved the problem, I have been training normally and I will report the results of the training later.
