### ISSUE TITLE
Why my program goes into infinite loop?

### ISSUE THREAD

**Issue by PCR11** [glample/tagger#72]
i run the train.py with eng.train,eng.testa,eng,testb.and it runs one day and one night,and it is still running now! is there some wrong? Or it takes so long time indeed?

**Comment by pvcastro** [comment]
It depends on your hardware, mainly on GPU or CPU. I haven't run for english language in a while, but I think it was taking, for me, several hours, almost a day. Anyway, the default number of epochs is 100, and train.py logs the progress by telling you the current epoch. Just check to see how is your progress.

**Comment by PCR11** [comment]
@pvcastro
Thank you very much! It exactly because of my hardware, then i modify my hidden layyer to 5 ,and my FB1 is 81.13 in my last time.
