### ISSUE TITLE
Cuda and Theano Version

### ISSUE THREAD

**Issue by nayakt** [glample/tagger#73]
Can you please tell which version of Cuda, CuDNN, and Theano is needed to run your code?

**Comment by sbmaruf** [comment]
So far I know, the original author, @glample run the code in a cpu.

**Comment by nayakt** [comment]
I am able to run it in GPU, but looks like it is running with batch size 1. Is there a easy way to increase the batch size?

**Comment by glample** [comment]
Unfortunately no, batch training was never implemented. The model was already converging fast enough on a CPU for the CoNLL datasets. Also, in my experiments the model was running faster on CPU than on GPU.

**Comment by nayakt** [comment]
Ok. Thanks !!!
