### ISSUE TITLE
Which tokenizer did you use?

### ISSUE THREAD

**Issue by janwendt** [glample/tagger#76]
Your documentation says: 

> The input file should contain one sentence by line, and they have to be tokenized. Otherwise, the tagger will perform poorly.

Simple Question: Which tokenizer did you use?

**Comment by glample** [comment]
Hi,

I only trained the model on the CoNLL datasets that were already tokenized, so I did not have to tokenized anything. Probably the Moses tokenizer should work well:
https://github.com/moses-smt/mosesdecoder/tree/master/scripts/tokenizer

**Comment by janwendt** [comment]
@glample can you give one example line how the input.txt should look like?

**Comment by glample** [comment]
Yes, you can check the data here:
https://github.com/glample/tagger/tree/master/dataset

**Comment by mrmotallebi** [comment]
@janwendt What did you eventually do?

**Comment by janwendt** [comment]
@mrmotallebi I am using the StanfordCoreNLP API which does a very good job but there are similar Python libs (NLTK is pretty good) as well.
Post that got me to the API: https://www.ibm.com/developerworks/community/blogs/nlp/entry/tokenization?lang=en

**Comment by glample** [comment]
I would personally recommend the Moses one, it's pretty standard, and very fast.

**Comment by bjtu-lucas-nlp** [comment]
@janwendt Do you have a domo of input.txt to the tagger.py?

**Comment by bjtu-lucas-nlp** [comment]
@janwendt It needn't . I have successed.

**Comment by gui-li** [comment]
@bjtu-lucas-nlp Could you please share an example of input.txt?
I have tried all kinds of combination but still get O tags of everything in the output.

**Comment by janwendt** [comment]
@gui-li if you have a column based data structure like:
`example1;example2;example3;`

the tokenized output and input.txt for your tagger should be:
```
example1
example2
example3
```

**Comment by gui-li** [comment]
@janwendt Thanks for replying.
