### ISSUE TITLE
SGD x Adam

### ISSUE THREAD

**Issue by pvcastro** [glample/tagger#79]
Hi there @glample 

Do you have any theories as to why, in your implementation, SGD is performing better than Adam optimizer (or any other optimizers, for that matter)? Do you think it's related to not having batch processing implemented?

Thanks!

**Comment by glample** [comment]
Hi,

My experience in general (and I know that many people had similar observations), is that SGD is what works best with batch size 1. Batch size 1 is also what works best in general, but people use bigger batch size (like 32 or 128) for training speed. When using bigger batch sizes, Adam usually gives better results than SGD. But well, this also depends a bit on the task.. But for NER I always observed that SGD was significantly the best.

**Comment by pvcastro** [comment]
Ok, thanks!
I'm presenting a paper based on your LSTM-CRF architecture on a conference for Portuguese NLP in september ("Portuguese Named Entity Recognition using LSTM-CRF" - [http://www.inf.ufrgs.br/propor-2018/accepted-papers/](http://www.inf.ufrgs.br/propor-2018/accepted-papers/)), so I'm getting ready for it. If you have any tips, they would be most welcome! Thanks!
