### ISSUE TITLE
Pretrained word embedding

### ISSUE THREAD

**Issue by HAWLYQ** [glample/tagger#83]
@glample Hi, in your paper, it was mentioned that you observed significant improvements using pretrained word embeddings. Could you share your pretrained English word embedding with me?

**Comment by glample** [comment]
Hi,

Yes, you can find them here: https://github.com/glample/tagger/issues/44

**Comment by enricoversino** [comment]
Hi.
I've tested your embeddings and were great. Could you share pretarained italian and french word embeddings?

**Comment by glample** [comment]
Hi,

I never trained embeddings on these languages, but you can have a look at the fastText embeddings, they should work very well for NER: https://fasttext.cc/docs/en/crawl-vectors.html

**Comment by sbmaruf** [comment]
@glample
I recently used your embeddings. 
your skip-n-gram embeddings given here are better than fasttext common-crawl vectors except the vectors for dutch. 
in case of fasttext, dutch pretrained embeddings gives around 85.75f1 score where skip-n-gram gives around 81.**

**Comment by enricoversino** [comment]
Thanks
