### ISSUE TITLE
Confusion about lable conversion.

### ISSUE THREAD

**Issue by sbmaruf** [glample/tagger#84]
Why do we convert NER lable from `iob` to `iobes`? While evaluating we again convert the `iobes` to `iob` to calculate the `f1` score. Is there any reason for that. Does that help gaining better F1 score?

**Comment by glample** [comment]
Yes, IOBES helps a bit during training, because these tags basically contain more signal than IOB. But overall this doesn't make a big difference.

**Comment by sbmaruf** [comment]
Thank you for your answer.
